language: scala
sudo: false
jdk: oraclejdk8
scala:
  - 2.12.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
